### PR TITLE
Add Contact Us title component

### LINKED ISSUE #45: Add Contact Us title component
Add component for title and subtitle text that make up left side of desktop [contact page](https://app.zeplin.io/project/5fc8757e071b5908d4857503/screen/5fcb0864d3eb954107c8619a).

### PR DESCRIPTION
**Pull request by krisbitney**
Added contact page and ContactTitleBox component. Closes #45.

### CODE REVIEW

**Review by benefacto — APPROVED** [review]

**Comment by krisbitney** [comment]
Requested new review because I added a commit. Sorry!

**Review by benefacto — APPROVED** [review]

**Comment by benefacto** [comment]
Can we fix that linting before merging?

**Comment by krisbitney** [comment]
> Can we fix that linting before merging?

Yes, of course. I get no linter or compilation warnings on my local machine. I'm not sure why, but github is complaining about the linter config file.

**Comment by benefacto** [comment]
@krisbitney [This](https://stackoverflow.com/a/60442807) may lead you toward a resolution for the linting errors.

**Pull request closed without merging**
