### PR TITLE
Added checkbox for email opt in to contact form

### LINKED ISSUE #212: Add marketing email opt-in checkbox to builder interest form
Ernesto: "hi! not sure if this would be the right channel for this request, but would it be possible to add a checkbox on the builder interest form at some point? we'd like to apply this best practice in order to be able to comply with hubspot's email guidelines (among other things); and make sure people opt in to receive emails from dOrg about other things - I can work on the specific wording. we could also potentially add it here [https://dorg.tech/#/contact](https://dorg.tech/#/contact) if possible."

image

### PR DESCRIPTION
**Pull request by Too-Far**
Added the checkbox, I believe the logic is handled on the backend? closes #212

### CODE REVIEW

**Comment by krisbitney** [comment]
The checkbox looks good, but it looks like adding the check box has squeezed the top and bottom margins a bit when viewed on my 13 inch screen. Could you make sure the vertical margins at the top and bottom are the same as those between the boxes? Or alternatively make whatever adjustment you think is best to make sure it still looks good on smaller screens.

image

Also, please don't merge this until we make sure the back end for this is working. I'll look into it asap.

**Comment by Too-Far** [comment]
100% I'll get that squared away tonight

**Comment by krisbitney** [comment]
> 100% I'll get that squared away tonight

Awesome. Make sure you can resize the window without breaking the UI. You may want to use vw for height because that's how the rest of the site was made.

I pushed a commit that you may want to review to make sure it looks right. I connected the checkbox with the form submission to make sure everything will work. I am actually still having an issue submitting forms so some adjustments might be needed, but I think it's an Airtable configuration issue so we might be good.

**Comment by krisbitney** [comment]
Hey, I just realized the issue Add marketing email opt-in checkbox to builder interest form #212 says to add a checkbox to the builder interest form, not the contact form. Let's pause on this PR.

**Comment by orishim** [comment]
Hey I think this would still be great for the contact form. Is anything stopping us from merging?

**Pull request closed without merging**
