### PR TITLE
update communities

### PR DESCRIPTION
**Pull request by orishim**

### CODE REVIEW

**Review by MuathJ — APPROVED** [review]

**Comment by orishim** [comment]
@MuathJ @krisbitney I added a few new clients to the homepage.

I'm having an issue with the icon for Rarible and Doingud that needs to be resolved before merging.

**Comment by krisbitney** [comment]
> @MuathJ @krisbitney I added a few new clients to the homepage.
> 
> I'm having an issue with the icon for Rarible and Doingud that needs to be resolved before merging.

What is the issue?

**Comment by orishim** [comment]
@krisbitney the icons for those two clients are not viewable until you hover over, they are entirely white. Could you take a look?

**Comment by krisbitney** [comment]
> @krisbitney the icons for those two clients are not viewable until you hover over, they are entirely white. Could you take a look?

Yeah, for sure

**Comment by krisbitney** [comment]
> @krisbitney the icons for those two clients are not viewable until you hover over, they are entirely white. Could you take a look?

The issue was with the way icons were made and the way the white color filter is applied. I fixed the issue but it required that I make some adjustments to the icons that may not be quite what you're looking for. Let me know what you think.

**Comment by orishim** [comment]
DoinGud looks fine, but the yellow is gone from Rarible now on hover over

**Review by krisbitney — APPROVED** [review]

**Pull request merged**
