### PR TITLE
New header

### PR DESCRIPTION
**Pull request by LilStark**
Updated the headers to link to airtable instead of separate pages like it was before

### CODE REVIEW

**Comment by orishim** [comment]
closes #264

**Review by krisbitney — CHANGES_REQUESTED** [review]
When I click the back button to return to the page, I see this: 
Screen Shot 2022-02-08 at 3 56 31 PM

**Comment by orishim** [comment]
@cedricwaxwing no strong opinion but that might be better. could you make that change?

**Comment by cedricwaxwing** [comment]
@orishim I can't seem to figure out how to open these in a new tab since they're using the navigateToPage() function via an onClick event. 🤔

**Comment by LilStark** [comment]
closing, all of these changes were applied in newHeaderWithBrandUpdate branch

**Pull request closed without merging**
